-- migrate:up

CREATE TABLE "session"
  ( id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , user_id    BIGINT      NOT NULL REFERENCES "user" (id)
  , token      UUID        NOT NULL
  , created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  , expires_at TIMESTAMPTZ NOT NULL
  );

-- We could also have used the session token itself as the primary key,
-- but I prefer to see the recent ones when I "select * limit 10" for
-- debugging, and we don't need an index on created_at.
CREATE INDEX ix_session_token ON "session" (token);

-- migrate:down

DROP TABLE "session";
