-- migrate:up

CREATE TABLE "market"
  ( id             BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , author_user_id BIGINT      NOT NULL REFERENCES "user" (id)
  , created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
  );

CREATE INDEX ix_market_author_user_id ON "market" (author_user_id);
CREATE INDEX ix_market_created_at ON "market" (created_at);

CREATE TABLE "market_title"
  ( id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , market_id  BIGINT      NOT NULL REFERENCES "market" (id)
  , title      TEXT        NOT NULL
  , created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  , CONSTRAINT title_length CHECK (length(title) <= 120)
  );

-- Facilitate getting a market's current title.
CREATE INDEX ix_market_title_market_id ON market_title (market_id, id);
CREATE FUNCTION market_current_title(bigint)
  RETURNS text
  LANGUAGE SQL
  STABLE
  RETURNS NULL ON NULL INPUT
  PARALLEL SAFE
  AS $$
    SELECT title
    FROM market_title
    WHERE market_id = $1
    ORDER BY id DESC
    LIMIT 1
  $$;

CREATE TABLE "market_description"
  ( id          BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , market_id   BIGINT      NOT NULL REFERENCES "market" (id)
  , description TEXT        NOT NULL
  , created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
  , CONSTRAINT description CHECK (length(description) <= 5000)
  );

-- Facilitate getting a market's current description.
CREATE INDEX ix_market_description_market_id ON market_description (market_id, id);
CREATE FUNCTION market_current_description(bigint)
  RETURNS text
  LANGUAGE SQL
  STABLE
  RETURNS NULL ON NULL INPUT
  PARALLEL SAFE
  AS $$
    SELECT description
    FROM market_description
    WHERE market_id = $1
    ORDER BY id DESC
    LIMIT 1
  $$;

-- migrate:down

DROP FUNCTION market_current_description;
DROP FUNCTION market_current_title;

DROP TABLE "market_description";
DROP TABLE "market_title";
DROP TABLE "market";
