-- migrate:up

CREATE TABLE "user_full_name"
  ( id         BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , user_id    BIGINT      NOT NULL REFERENCES "user" (id)
  , full_name  TEXT        NOT NULL
  , created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );

-- Facilitate getting a user's current full name.
CREATE INDEX ix_user_full_name_user_id_id ON user_full_name (user_id, id);
CREATE FUNCTION user_current_full_name(bigint)
    RETURNS text
    LANGUAGE SQL
    STABLE
    RETURNS NULL ON NULL INPUT
    PARALLEL SAFE
    AS $$
        SELECT full_name
        FROM user_full_name
        WHERE user_id = $1
        ORDER BY id DESC
        LIMIT 1
    $$;

-- For clarity, we distinguish the "username" and the "full name".
ALTER TABLE "user_name" RENAME COLUMN "name" TO "username";
ALTER TABLE "user_name" RENAME TO "user_username";
ALTER INDEX ix_user_name_user_id_id RENAME TO ix_user_username_user_id_id;
ALTER INDEX ix_user_name_unique RENAME TO ix_user_username_unique;
DROP FUNCTION user_current_name;
CREATE FUNCTION user_current_username(bigint)
    RETURNS text
    LANGUAGE SQL
    STABLE
    RETURNS NULL ON NULL INPUT
    PARALLEL SAFE
    AS $$
        SELECT username
        FROM user_username
        WHERE user_id = $1
        ORDER BY id DESC
        LIMIT 1
    $$;

-- migrate:down

DROP FUNCTION user_current_full_name;
DROP TABLE "user_full_name";

ALTER TABLE "user_username" RENAME COLUMN "username" TO "name";
ALTER TABLE "user_username" RENAME TO "user_name";
ALTER INDEX ix_user_username_user_id_id RENAME TO ix_user_name_user_id_id;
ALTER INDEX ix_user_username_unique RENAME TO ix_user_name_unique;
DROP FUNCTION user_current_username;
CREATE FUNCTION user_current_name(bigint)
    RETURNS text
    LANGUAGE SQL
    STABLE
    RETURNS NULL ON NULL INPUT
    PARALLEL SAFE
    AS $$
        SELECT name
        FROM user_name
        WHERE user_id = $1
        ORDER BY id DESC
        LIMIT 1
    $$;
