-- migrate:up

CREATE TABLE "outcome"
  ( id             BIGINT      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , market_id      BIGINT      NOT NULL REFERENCES "market" (id)
  , name           TEXT        NOT NULL
  , color          TEXT        NOT NULL
  , value_float    FLOAT8      NULL
  , value_datetime TIMESTAMPTZ NULL
  , CONSTRAINT name_length  CHECK (length(name) <= 35)
  , CONSTRAINT color_format CHECK (color ~ '^#[0-9a-f]{6}$')
  , CONSTRAINT single_type  CHECK (num_nonnulls(value_float, value_datetime) <= 1)
  );

COMMENT ON TABLE "outcome" IS '
  There are three types of outcome:
  1. Discrete (like yes/no). Both value_* fields are null.
  2. Continuous number. value_float must be non-null.
  3. Continuous datetime. value_datetime must be non-null.
  All the outcomes for a market must have the same type,
  but this is not enforced in the schema.
';

CREATE INDEX ix_outcome_market_id ON "outcome" (market_id);

-- migrate:down

DROP TABLE "outcome";
