-- migrate:up

ALTER TYPE transaction_type RENAME TO subtransaction_type;

ALTER TABLE "mutation" RENAME COLUMN transaction_id TO subtransaction_id;
ALTER TABLE "transaction" RENAME TO "subtransaction";
ALTER TABLE "subtransaction"
  DROP COLUMN creator_user_id,
  DROP COLUMN created_at;


CREATE TYPE transaction_type AS ENUM
  ( 'income'
  , 'fund_market'
  , 'trade'
  , 'subsidize'
  , 'resolve'
  , 'unresolve'
  );

CREATE TABLE "transaction"
  ( id              BIGINT           NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , type            transaction_type NOT NULL
  , creator_user_id BIGINT               NULL REFERENCES "user" (id)
  , created_at      TIMESTAMPTZ      NOT NULL DEFAULT now()
  );

CREATE INDEX ix_transaction_creator_user_id
  ON transaction (creator_user_id)
  WHERE creator_user_id IS NOT NULL;

CREATE INDEX ix_transaction_created_at
  ON transaction USING BRIN (created_at)
  WITH (autosummarize = true);

ALTER TABLE "subtransaction" ADD COLUMN transaction_id BIGINT NOT NULL REFERENCES "transaction" (id);
CREATE INDEX ix_subtransaction_transaction_id ON subtransaction (transaction_id);

-- migrate:down

ALTER TABLE "subtransaction" DROP COLUMN transaction_id;

DROP TABLE "transaction";
DROP TYPE "transaction_type";

ALTER TYPE subtransaction_type RENAME TO transaction_type;

ALTER TABLE "mutation" RENAME COLUMN subtransaction_id TO transaction_id;
ALTER TABLE "subtransaction" RENAME TO "transaction";
ALTER TABLE "transaction"
  ADD COLUMN creator_user_id BIGINT NULL REFERENCES "user" (id),
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX ix_transaction_creator_user_id
  ON transaction (creator_user_id)
  WHERE creator_user_id IS NOT NULL;

CREATE INDEX ix_transaction_created_at
  ON transaction USING BRIN (created_at)
  WITH (autosummarize = true);
